name: CI

on:
  push:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  check:
    uses: input-output-hk/catalyst-ci/.github/workflows/check.yml@master
    with:
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
    secrets:
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}
  release:
    uses: input-output-hk/catalyst-ci/.github/workflows/release.yml@master
    needs: [check]
    with:
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
    secrets:
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}
  publish:
    uses: input-output-hk/catalyst-ci/.github/workflows/publish.yml@master
    needs: [release]
    with:
      aws_ecr_registry: 332405224602.dkr.ecr.eu-central-1.amazonaws.com
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
    secrets:
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}
  deploy:
    uses: input-output-hk/catalyst-ci/.github/workflows/deploy.yml@deploy-action
    #if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: [publish]
    with:
      deployment_repo: input-output-hk/catalyst-world
      images: |
        milestone-module-frontend
    secrets:
      token: ${{ secrets.CI_BOT_TOKEN }}